# app.py

import streamlit as st
from main import evaluate_response
import json

st.set_page_config(page_title="eval.ai", layout="wide", page_icon="🔬")

# ── Translations ───────────────────────────────────────────────────────────────
T = {
    "en": {
        "badge": "UX-driven AI evaluation",
        "title_line1": "Evaluate LEO's",
        "title_line2": "responses",
        "subtitle": "The virtual companion by Dassault Systèmes",
        "desc": "Paste a question and LEO's response. Get an instant UX evaluation based on proven quality criteria.",
        "link": "See the 10 heuristics list in details →",
        "label_prompt": "USER QUESTION",
        "label_response": "AGENT RESPONSE",
        "placeholder_prompt": "Paste the question asked to the agent…",
        "placeholder_response": "Paste the response generated by the agent…",
        "button": "⚡ Run Evaluation",
        "spinner": "Evaluating…",
        "results_title": "Criteria Details",
        "suggestions_title": "🌐 Global Improvement Suggestions",
        "observed": "Observed",
        "justification": "Justification",
        "advice": "Advice",
        "na": "N/A",
        "warning": "⚠️ Please fill in both fields before running the evaluation.",
        "error": "Error",
    },
    "fr": {
        "badge": "Évaluation UX par IA",
        "title_line1": "Évaluez les réponses",
        "title_line2": "de LEO",
        "subtitle": "Le virtual companion de Dassault Systèmes",
        "desc": "Collez une question et la réponse de LEO. Obtenez une évaluation UX instantanée basée sur des critères de qualité éprouvés.",
        "link": "Voir la liste des 10 heuristiques en détail →",
        "label_prompt": "QUESTION UTILISATEUR",
        "label_response": "RÉPONSE DE L'AGENT",
        "placeholder_prompt": "Collez la question posée à l'agent…",
        "placeholder_response": "Collez la réponse générée par l'agent…",
        "button": "⚡ Lancer l'évaluation",
        "spinner": "Évaluation en cours…",
        "results_title": "Détail des critères",
        "suggestions_title": "🌐 Suggestions d'amélioration globales",
        "observed": "Observé",
        "justification": "Justification",
        "advice": "Conseil",
        "na": "N/A",
        "warning": "⚠️ Remplis les deux champs avant de lancer l'évaluation.",
        "error": "Erreur",
    }
}

if "lang" not in st.session_state:
    st.session_state.lang = "en"

st.markdown("""
<style>
  @import url('https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Inter:wght@300;400;500;600;700&display=swap');

  .stApp { background-color: #0d0d0d; color: #e0e0e0; }
  * { box-sizing: border-box; }

  .hero { text-align: center; padding: 2rem 1rem 3rem 1rem; max-width: 700px; margin: 0 auto; }
  .hero-badge {
    display: inline-flex; align-items: center; gap: 0.4rem;
    background: #111; border: 1px solid #2a2a2a; border-radius: 20px;
    padding: 0.3rem 1rem; font-family: 'Space Mono', monospace;
    font-size: 0.75rem; color: #ccc; margin-bottom: 1.5rem;
  }
  .dot { width: 7px; height: 7px; background: #0050c8; border-radius: 50%; display: inline-block; }
  .hero-title { font-family: 'Inter', sans-serif; font-size: 3rem; font-weight: 700; color: white; line-height: 1.15; margin-bottom: 0.3rem; }
  .accent { color: #4d8bff; }
  .hero-subtitle { font-family: 'Inter', sans-serif; font-size: 1rem; color: #aaa; margin-bottom: 1rem; }
  .hero-desc { font-family: 'Inter', sans-serif; font-size: 0.9rem; color: #888; line-height: 1.6; margin-bottom: 1rem; }
  .hero-link { font-family: 'Inter', sans-serif; font-size: 0.85rem; color: #4d8bff; }

  /* Form labels — bien visibles */
  .form-label {
    font-family: 'Space Mono', monospace;
    font-size: 0.72rem;
    letter-spacing: 0.12em;
    color: #aaa;
    text-transform: uppercase;
    margin-bottom: 0.5rem;
  }

  /* Textarea */
  textarea {
    background: #111 !important;
    border: 1px solid #2a2a2a !important;
    border-radius: 10px !important;
    color: #e0e0e0 !important;
    font-family: 'Space Mono', monospace !important;
    font-size: 0.85rem !important;
  }
  textarea:focus { border-color: #0050c8 !important; box-shadow: 0 0 0 2px rgba(0,80,200,0.2) !important; }
  textarea::placeholder { color: #555 !important; }

  .stButton { display: flex; justify-content: center; margin-top: 1.5rem; }
  .stButton > button {
    background: linear-gradient(90deg, #003189, #0050c8); color: white; border: none;
    padding: 0.75rem 2.5rem; border-radius: 10px; font-family: 'Space Mono', monospace;
    font-size: 0.9rem; font-weight: 700; letter-spacing: 0.03em;
  }
  .stButton > button:hover { opacity: 0.85; }

  /* Radio flag */
  div[data-testid="stRadio"] { margin-top: 0.8rem; }
  div[data-testid="stRadio"] > div { gap: 0.3rem !important; }
  div[data-testid="stRadio"] label {
    display: flex !important; align-items: center; justify-content: center;
    background: #111; border: 1px solid #2a2a2a; border-radius: 8px;
    padding: 0.25rem 0.6rem; cursor: pointer; font-size: 1.4rem !important;
    color: white !important; min-width: 2.5rem;
  }
  div[data-testid="stRadio"] label:has(input:checked) { border-color: #0050c8; background: #0a1a3a; }
  div[data-testid="stRadio"] input { display: none; }

  .results-title { font-family: 'Inter', sans-serif; font-size: 1.3rem; font-weight: 700; color: white; margin: 2rem 0 1.5rem 0; border-bottom: 1px solid #1e1e1e; padding-bottom: 0.8rem; }

  .criterion-card { background: #111; border: 1px solid #1e1e1e; border-left: 4px solid #0050c8; border-radius: 10px; padding: 1.2rem 1.5rem; margin-bottom: 1rem; }
  .criterion-card.red    { border-left-color: #e53935; }
  .criterion-card.orange { border-left-color: #f57c00; }
  .criterion-card.green  { border-left-color: #2e7d32; }
  .criterion-card.gray   { border-left-color: #444; }

  .crit-header { display: flex; flex-direction: row-reverse; justify-content: flex-end; align-items: center; gap: 1rem; margin-bottom: 0.8rem; }
  .crit-name { font-family: 'Inter', sans-serif; font-weight: 600; font-size: 1rem; color: #e0e0e0; }
  .score-pill { font-family: 'Space Mono', monospace; font-size: 1.1rem; font-weight: 700; padding: 0.3rem 1rem; border-radius: 20px; }
  .pill-red    { background: #2a1010; color: #e53935; }
  .pill-orange { background: #2a1a00; color: #f57c00; }
  .pill-green  { background: #0a2a0a; color: #4caf50; }
  .pill-gray   { background: #1a1a1a; color: #777; }

  .crit-detail { font-family: 'Inter', sans-serif; font-size: 0.92rem; color: #c0c0c0; margin-top: 0.6rem; line-height: 1.7; }
  .crit-detail strong { color: #e0e0e0; }

  .suggestions-box { background: #0a0f1a; border: 1px solid #1a2a4a; border-radius: 10px; padding: 1.5rem; margin-top: 2rem; }
  .suggestions-box h3 { font-family: 'Inter', sans-serif; color: #4d8bff; font-size: 1rem; margin-bottom: 1rem; }
  .suggestions-box li { font-family: 'Inter', sans-serif; font-size: 0.92rem; color: #c0c0c0; margin-bottom: 0.5rem; line-height: 1.7; }

  #MainMenu, footer, header { visibility: hidden; }
  .block-container { padding-top: 0 !important; }
  label { display: none !important; }
  div[data-testid="stRadio"] label { display: flex !important; }
  hr { display: none; }
</style>
""", unsafe_allow_html=True)

# ── Navbar ─────────────────────────────────────────────────────────────────────
col_nav1, col_nav2 = st.columns([8, 1])
with col_nav1:
    st.markdown("""
    <div style="display:flex; align-items:center; gap:0.5rem; padding: 1rem 0 1rem 0; border-bottom: 1px solid #1e1e1e; margin-bottom: 2rem;">
      <div style="background:#0050c8; color:white; width:32px; height:32px; border-radius:6px; display:flex; align-items:center; justify-content:center; font-weight:900; font-size:0.8rem;">3DS</div>
      <span style="font-family:'Inter',sans-serif; font-weight:700; font-size:1.1rem; color:white;">eval.ai</span>
    </div>
    """, unsafe_allow_html=True)
with col_nav2:
    lang_choice = st.radio(
        "lang",
        ["🇫🇷", "🇬🇧"],
        horizontal=True,
        label_visibility="collapsed",
        index=0 if st.session_state.lang == "fr" else 1
    )
    st.session_state.lang = "fr" if lang_choice == "🇫🇷" else "en"

lang = st.session_state.lang
t = T[lang]

# ── Hero ───────────────────────────────────────────────────────────────────────
st.markdown(f"""
<div class="hero">
  <div class="hero-badge"><span class="dot"></span> {t["badge"]}</div>
  <div class="hero-title">{t["title_line1"]}<br><span class="accent">{t["title_line2"]}</span></div>
  <div class="hero-subtitle">{t["subtitle"]}</div>
  <div class="hero-desc">{t["desc"]}</div>
  <span class="hero-link">{t["link"]}</span>
</div>
""", unsafe_allow_html=True)

# ── Inputs ─────────────────────────────────────────────────────────────────────
col1, col2 = st.columns(2)
with col1:
    st.markdown(f'<div class="form-label">{t["label_prompt"]}</div>', unsafe_allow_html=True)
    prompt = st.text_area("q", height=200, placeholder=t["placeholder_prompt"], label_visibility="collapsed")
with col2:
    st.markdown(f'<div class="form-label">{t["label_response"]}</div>', unsafe_allow_html=True)
    response_agent = st.text_area("r", height=200, placeholder=t["placeholder_response"], label_visibility="collapsed")

if st.button(t["button"]):
    if prompt and response_agent:
        with st.spinner(t["spinner"]):
            evaluation = evaluate_response(prompt, response_agent, language=lang)

        try:
            from json_repair import repair_json
            data = json.loads(repair_json(evaluation))
        except Exception as e:
            st.error(f"{t['error']} : {type(e).__name__} — {e}")
            st.code(evaluation)
            st.stop()

        st.markdown(f'<div class="results-title">{t["results_title"]}</div>', unsafe_allow_html=True)

        for criterion, content in data["evaluation"].items():
            criterion_name = criterion.replace("_", " ").title()
            score = content.get("score")
            applicable = content.get("applicable", True)

            if not applicable or score is None:
                color = "gray"; display_score = t["na"]; pill = "pill-gray"
            elif score <= 2:
                color = "red"; display_score = f"{score} / 5"; pill = "pill-red"
            elif score <= 4:
                color = "orange"; display_score = f"{score} / 5"; pill = "pill-orange"
            else:
                color = "green"; display_score = f"{score} / 5"; pill = "pill-green"

            observed = content.get("observed_elements", "")
            justif   = content.get("justification", "")
            advice   = content.get("improvement_advice", "")

            html = f'<div class="criterion-card {color}"><div class="crit-header"><div class="crit-name">{criterion_name}</div><div class="score-pill {pill}">{display_score}</div></div>'
            if observed:
                html += f'<div class="crit-detail"><strong>🔍 {t["observed"]}:</strong> {observed}</div>'
            if justif:
                html += f'<div class="crit-detail"><strong>📋 {t["justification"]}:</strong> {justif}</div>'
            if advice and applicable and score is not None and score < 5:
                html += f'<div class="crit-detail"><strong>💡 {t["advice"]}:</strong> {advice}</div>'
            html += "</div>"
            st.markdown(html, unsafe_allow_html=True)

        suggestions = data.get("global_improvement_suggestions", [])
        if suggestions:
            s_html = f'<div class="suggestions-box"><h3>{t["suggestions_title"]}</h3><ul>'
            for s in suggestions:
                s_html += f"<li>{s}</li>"
            s_html += "</ul></div>"
            st.markdown(s_html, unsafe_allow_html=True)

    else:
        st.warning(t["warning"])